### ISSUE TITLE
Compiling issues

### ISSUE THREAD

**Issue by CorranEveryone** [NotAwesome2/Not-Awesome-Script#4]
############################################################
Errors when compiling /home/container/plugins/ccs.cs
############################################################

Error on line 443:
        public const Chat.PersistentMessage.Priority replyPriority = Chat.PersistentMessage.Priority.Highest;
                                       ^-- Error #CS0426 - The nested type `PersistentMessage' does not exist in the type `MCGalaxy.Chat'

**Comment by Goodlyay** [comment]
Update your server to the latest MCGalaxy build
