### ISSUE TITLE
Errors when compiling

### ISSUE THREAD

**Issue by RonXTCdaBass** [NotAwesome2/Not-Awesome-Script#6]
```

############################################################
Errors when compiling C:\Users\Public\Downloads\Server_CC_MCGalaxy\plugins\ccs.cs
############################################################

Error on line 2481:
            return Wildcard.Filter(keys, keyword, key => key);
                   ^-- Error #CS0103 - Der Name 'Wildcard' ist im aktuellen Kontext nicht vorhanden.

-------------------------

Error on line 2529:
            if (dict.TryGetValue(stringName, out string dicValue)) { value = dicValue; }
                                                        ^-- Error #CS1525 - UngÃ¼ltiger Ausdruck 'string'.

-------------------------

Error on line 2529:
            if (dict.TryGetValue(stringName, out string dicValue)) { value = dicValue; }
                                                                ^-- Error #CS1002 - ; erwartet.

-------------------------

Error on line 2529:
            if (dict.TryGetValue(stringName, out string dicValue)) { value = dicValue; }
                                                                ^-- Error #CS1525 - UngÃ¼ltiger Ausdruck ')'.

-------------------------

Error on line 2529:
            if (dict.TryGetValue(stringName, out string dicValue)) { value = dicValue; }
                                                                 ^-- Error #CS1002 - ; erwartet.

-------------------------  

```

and not enough...

what is this?
the same file: ccs.cs 
lines 858 - 862

`        static string fullPath(Level level) { return directory + fileName(level); }
        static string directory { get { return "/home/na2/Website-Files/" + folder; } }
        static string folder { get { return "osscripts/"; } }
        static string fileName(Level level) { return level.name.ToLower() + "-" + GetMD5(level) + Script.EXT; }
        static string url(Level level) { return "https://notawesome.cc/" + folder + fileName(level); }`

both, the folder home/na2/website-files   and  the Web at notawesome.cc don't exist.  

:(

running MCGalaxy 1.9.4.9 and tested at win7 x86 & 64bit . the same

**Comment by Goodlyay** [comment]
Compilation errors should be fixed now, but you will need to update your MCGalaxy to the latest [development build](https://mcgala.xyz/nightlies).


`what is this?
the same file: ccs.cs
lines 858 - 862`

That is to let users download their scripts if they accidentally delete their local copy. 

You need to run your own web server and change the URL to your own to use that feature. You don't need it for normal script use.

**Comment by Goodlyay** [comment]
Also, make sure you get updated _na2lib.cs
